TxnRs.exit_timestamp
TxnRs.received_timestamp
TxnRs.posted_date
TxnRs.serial_num
TxnRs.entrySpAccountNo
TxnRs.entrySpId
TxnRs.entrySpName
TxnRs.exitSpAccountNo
TxnRs.exitSpId
TxnRs.exitSpName
TxnRs.entryLocId
TxnRs.entryLocName
TxnRs.exitLocId
TxnRs.exitLocName
TxnRs.tag_serial_num
TxnRs.vehicle_plate_num
TxnRs.vehicle_class
TxnRs.tt_type
TxnRs.tt_type_desc
TxnRs.category
TxnRs.sub_category
TxnRs.tdebit_credit
TxnRs.mlffOrder.order_number
TxnRs.tranId
TxnRs.tran_amt
TxnRs.std_plan_id
TxnRs.payment_id
TxnRs.source_of_fund
TxnRs.mlffOrder.payment_option_name
TxnRs.walletUUID
TxnRs.paymentResponseTime
TxnRs.error_code_id
TxnRs.response_code
TxnRs.error_description